```{r}
library(tidyverse)
library(here)
source(here("triangulation_distances.R"))

df_full = read.csv("./data/day_3_comparisons.csv", header=TRUE)

#lets look at T D3 and control D3
df = df_full[df_full$treatment %in% c("T cells","2HC T cells"),]

#lets look at the productive T cells vs Unproductive T cells Tumor
#df = df_full[df_full$treatment %in% c("T cells"),]
#df = df[df$Neighborhood.common2 %in% c("Productive T Cell & Tumor","Unproductive T Cell & Tumor"),]

colnames(df)[1] = "index"
#remove other unncessary columns
df = df[,c("index","x", "y", "treatment","unique_region","Neighborhood.common2","Cell.common")] 

metadata <- df %>%
  select(treatment, unique_region) %>%
  distinct(.keep_all = TRUE)
```

```{R}
cmap_celltypes = c("B cell" = "#377EB8",
                  "CD4+ T cell " = "#17ddbf",
                  "CD4+ Treg" = "#068C64",
                  "CD8+ T cell" = "#E41A1C",
                  "CD8+ T cell PD1+ " = "#9A372E",
                  "DC" = "#2eb921",
                  #"DC CD86+" = "#91b715",
                  #"DC TCF7" = "#DA6328",
                  "Endothelial" = "#32322e",
                  "Epithelial" = "#797E82",
                  "Macrophage" = "#F781BF",
                  "Macrophage CD169+" = "#F056A8",
                  #"Macrophage CD169+ PD1+" =  "#F056A8", 
                  #"Macrophage PD1+" = "#F056A8",
                  "NK" = "#060506",
                  "Neutrophil" = "#E037E3",
                  "Stromal" = "#654c4c",
                  "Tumor" = "#F4CAE4",
                  #"Tumor CD44hi" = "#FDCDAC",
                  #"Tumor CD71hi Ki67+" = "#B19595",
                  #"Tumor CD71hi Ki67+" = "#FFF2AE",
                  "Tumor Ki67+" = "#e3b369",
                  "Tumor PD1+ MHCI+" = "#B09266"
                  #"Tumor TYRP1hi" = "#EECFA0",
                  #"Tumor TYRP1hi Ki67+" = "#F1E2CC"
                  )
ggplot(data = df,
       mapping = aes(x = x, y = y, 
                     fill = Cell.common, color = Cell.common)) +
  geom_point(shape = 21, size = 0.5) +
  theme_classic() +
  facet_wrap(~unique_region) +
  scale_fill_manual(values = cmap_celltypes) +
  scale_color_manual(values = cmap_celltypes) +
  guides(fill = guide_legend(override.aes = list(size = 3)),
         color = "none") +
  labs(fill = "Cell Annotation") +
  ggtitle("Cell type annotations")
```

```{r}
triangulation_distances <- get_triangulation_distances(df_input = df,
                                                       id = "index",
                                                       x_pos = "x",
                                                       y_pos = "y",
                                                       cell_type = "Cell.common",
                                                       region = "unique_region")
head(triangulation_distances)

# Calculate the average distance between different cell types
# This can be interpreted as
# "The average distance between cell type X and cell type Y is ___."
per_celltype_summary <- per_cell_summary %>%
  group_by(celltype1, celltype2, region) %>%
  summarize(mean_dist = mean(per_cell_mean_dist)) %>%
  ungroup()
head(per_celltype_summary)

# Calculate the average distance to different cell types on a per individual cell level
# This can be interpreted as
# "For cell #1, the average distance to a cell of type X is ____."
per_cell_summary <- triangulation_distances %>%
  group_by(celltype1_index, celltype1, celltype2, unique_region) %>%
  summarize(per_cell_mean_dist = mean(distance)) %>%
  ungroup()
head(per_cell_summary)
```
```{R}
#For the permutation tests, cell type annotations are shuffled on a per region basis.
#An example of what is happening can be seen in this single iteration
df_shuffled <- shuffle_annotations(df_input = df,
                                   cell_type = "Cell.common",
                                   region = "unique_region",
                                   permutation = 1)

ggplot(data = df_shuffled,
       mapping = aes(x = x, y = y, 
                     fill = random_annotations, color = random_annotations)) +
  geom_point(shape = 21, size = 0.5) +
  theme_classic() +
  facet_wrap(~unique_region) +
  scale_fill_manual(values = cmap_celltypes) +
  scale_color_manual(values = cmap_celltypes) +
  guides(fill = guide_legend(override.aes = list(size = 3)),
         color = "none") +
  labs(fill = "Cell Annotation") +
  ggtitle("Shuffled cell type annotations")
```

```{R}
# Iterations
# In the iterated distances, distances are summarized per region for each iteration.
#Note: you don't need to shuffle the cell annotations yourself, it's done in the iteration for you
iterated_triangulation_distances <- iterate_triangulation_distances(df_input = df,
                                                                      id = "index",
                                                                      x_pos = "x",
                                                                      y_pos = "y",
                                                                      cell_type = "Cell.common",
                                                                      region = "unique_region",
                                                                      num_iterations = 100)
head(iterated_triangulation_distances)

ggdf <- iterated_triangulation_distances %>%
  left_join(metadata,
            by = c("unique_region")) %>%
  dplyr::filter(celltype1 == "CD8+ T cell", celltype2 == "Macrophage") 

ggplot(data = ggdf,
       mapping = aes(x = mean_dist, fill = treatment, color = treatment)) +
  geom_density() +
  theme_bw() +
  facet_wrap(~treatment)
```

```{r}
# Set distance threshold for observed cell-cell interactions
distance_threshold = 128 # corresponds to 100um

# Reformat observed dataset
observed_distances <- triangulation_distances %>%
  # Append metadata
  left_join(metadata,
            by = c("unique_region")) %>%
  dplyr::filter(distance <= distance_threshold) %>%
  # Calculate the average distance to every cell type for each cell
  group_by(celltype1_index, celltype1, celltype2, treatment, unique_region) %>%
  summarize(mean_per_cell = mean(distance)) %>%
  ungroup() %>%
  # Calculate the average distance between cell type to cell type on a per group basis
  group_by(celltype1, celltype2, treatment) %>%
  summarize(observed = list(mean_per_cell),
            observed_mean = mean(unlist(observed), na.rm = TRUE)) %>%
  ungroup()

# Reformat exepcted dataset
expected_distances <- iterated_triangulation_distances %>%
  # Append metadata
  left_join(metadata,
            by = c("unique_region")) %>%
  dplyr::filter(mean_dist <= distance_threshold) %>%
  # Calculate expected mean distance and list values
  group_by(celltype1, celltype2, treatment) %>%
  summarize(expected = list(mean_dist),
            expected_mean = mean(mean_dist, na.rm = TRUE)) %>%
  ungroup() 

# Calculate pvalues and log fold differences
distance_pvals <- expected_distances %>%
  left_join(observed_distances,
            by = c("celltype1", "celltype2", "treatment")) %>%
  # Calculate wilcoxon test between observed and expected distances
  group_by(celltype1, celltype2, treatment) %>%
  mutate(pvalue = wilcox.test(unlist(expected), unlist(observed), exact = FALSE)$p.value) %>%
  ungroup() %>%
  select(-observed, -expected) %>%
  # Calculate log fold enrichment
  mutate(logfold_group = log2(observed_mean/expected_mean),
         interaction = paste0(celltype1, " --> ", celltype2)) 
  
# Get order of plot by magnitude of logfold differences between groups
ord <- (distance_pvals %>%
          select(interaction, treatment, logfold_group) %>%
          spread(key = treatment, value = logfold_group) %>%
          mutate(difference = (`2HC T cells` - `T cells`)) %>%
          dplyr::filter(!is.na(difference)) %>%
          arrange(`T cells`))$interaction
  
# Assign interaction order
distance_pvals$interaction <- factor(distance_pvals$interaction,
                                     levels = ord)

# Dumbbell plot
#distance_pvals_CD8 = distance_pvals[distance_pvals$celltype1 == "CD8+ T cell PD1+",]
distance_pvals_CD8 = distance_pvals[distance_pvals$celltype1 == "CD8+ T cell",]

data = distance_pvals %>%
         dplyr::filter(!is.na(interaction))

distance_pvals$pairs = paste0(distance_pvals$celltype1, "_", distance_pvals$celltype2)
distance_pvals_sub = distance_pvals[distance_pvals$pairs %in% c("CD4+ Treg_Stromal", "CD8+ T cell_NK", "DC_NK", "NK_CD8+ T cell", "NK_CD8+ T cells", "Stromal_CD4+ Treg", "CD4+ T cell_Neutrophil", "CD8+ T cell PD1+_NK", "CD4+ T cell_CD4+ T cell", "CD4+ T cell_CD8+ T cell", "CD8+ T cell_Tumor PDL1+ MHCI+"), ]

ggplot(data = distance_pvals_sub %>%
         dplyr::filter(!is.na(interaction))) +
  geom_vline(mapping = aes(xintercept = 0), linetype = "dashed") +
  geom_line(mapping = aes(x = logfold_group, y = interaction),
            na.rm = TRUE) +
  geom_point(mapping = aes(x = logfold_group, y = interaction, fill = treatment, shape = treatment), 
             size = 4, stroke = 0.5, na.rm = TRUE) +
  scale_shape_manual(values = c(24, 22)) + scale_fill_manual(values = c("#00BFC4","#F8766D")) +
  theme_bw()+
  theme(panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        axis.text.y = element_text(size = 16),
        axis.text.x = element_text(size = 16, angle = 45, hjust = 1),
        axis.title.y = element_text(size = 16),
        axis.title.x = element_text(size = 16))
        #,axis.text.y = element_text(size = 4)
```

```{r}
#implment this as code to trim out the interactions
#Find -0.5 log fold for 2HC 
#find the difference between 2HC and T to be greater than 0.5  

```